loadTimeData.data = {
  bestScore: "Best $1 $2 $3",
  bestScoreFlyout: "Best score: $1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "Cancel",
  close: "Close",
  code: "Cheat code activated!",
  codeCheat: "Cheat code activated! $1",
  codeScoring: "Scoring turned off for this round.",
  endlessBestScore: -1,
  endlessDescriptor: "distance",
  endlessModeTitleInline: "Endless:",
  endlessTitle: "Endless",
  endlessUnit: "m",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "Game credits",
  gameCreditsDialogTitle: "Game credits",
  gameMode: "Game mode changed to $1",
  gameModeSelectLabel: "Game mode",
  gameModeSelectLabelDisabled: "Game mode (start new game to change)",
  gameSettings: "Game settings",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "High visiblity",
  howToPlayButton: "How to play",
  howToPlayControllerBoost: "Press RT to use your speed boost",
  howToPlayControllerMovement: "Use the thumbstick or D-pad to steer",
  howToPlayControllerRefresh: "Press LB+RB to restart the game",
  howToPlayDialogTitle: "How to play",
  howToPlayEndless:
    "Travel as far as you can and rescue a friend for help with enemies",
  howToPlayKeyboardBoost: "Press `F` to use your speed boost",
  howToPlayKeyboardMovement: "Use the arrow or `WASD` keys to steer",
  howToPlayKeyboardRefresh: "Refresh the page to restart the game",
  howToPlayMouseBoost: "Right-click to use your speed boost",
  howToPlayMouseMovement: "Move the mouse to steer",
  howToPlayMouseRefresh: "Refresh the page to restart the game",
  howToPlayTimeTrial:
    "Reach the end as fast as you can and collect coins to subtract time",
  howToPlayTouchBoost: "Swipe down twice to use your speed boost",
  howToPlayTouchMovement: "Swipe or tap to steer",
  howToPlayTouchRefresh: "Refresh the page to restart the game",
  howToPlayZigZag: "Pass through as many gates as you can in a row",
  is_windows_xbox_sku: "false",
  keyboardAction: "spacebar",
  language: "en",
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "surf",
  menuInfo: "to start playing",
  mouseAction: "double click",
  newBestScore: "New best $1 $2 $3",
  newGame: "Start new game",
  off: "Off",
  on: "On",
  overInfo: "to play again",
  overTitle: "Nice try!",
  pauseInfo: "to resume playing",
  pauseTitle: "Game paused",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "Reduced speed",
  resetAllStats: "Reset all stats",
  resetAllStatsDialogText:
    "Are you sure you want to reset all your game stats, including your high scores?",
  resetAllStatsDialogTitle: "Reset all stats",
  share: "Share with a friend",
  shareCopy: "Copy",
  shareLink: "edge://surf",
  shareLinkCopied: "Copied!",
  skiTheme: "Let's ski",
  specialThanks: "Special thanks:",
  surfTheme: "Let's surf",
  textdirection: "ltr",
  theme: "Theme changed to $1",
  themeSelectLabel: "Theme",
  timetrialBestScore: -1,
  timetrialDescriptor: "time",
  timetrialModeTitleInline: "Time trial:",
  timetrialTitle: "Time trial",
  timetrialUnit: "s",
  touchAction: "double tap",
  zigzagBestScore: -1,
  zigzagDescriptor: "streak",
  zigzagModeTitleInline: "Zig zag:",
  zigzagTitle: "Zig zag",
  zigzagUnit: "gates",
};
